apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  name: my-cloud-run-service
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: '{"collector":["app"]}'
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      containers:
      - image: "IMAGE_PLACEHOLDER"
        env:
        - name: TELEGRAM_BOT_TOKEN
          value: "TELEGRAM_BOT_TOKEN_PLACEHOLDER"
        - name: GCP_PROJECT_ID
          value: "GCP_PROJECT_ID_PLACEHOLDER"
        - name: CMC_API_KEY
          value: "CMC_API_KEY_PLACEHOLDER"
        - name: UPSTASH_REDIS_URL
          value: "UPSTASH_REDIS_URL_PLACEHOLDER"
        - name: KAFKA_BOOTSTRAP_SERVER                                                                                                                                                                                                                                  
          value: "KAFKA_BOOTSTRAP_SERVER_PLACEHOLDER"                                                                                                                                                                                                                   
        - name: KAFKA_API_KEY                                                                                                                                                                                                                                           
          value: "KAFKA_API_KEY_PLACEHOLDER"                                                                                                                                                                                                                            
        - name: KAFKA_API_SECRET                                                                                                                                                                                                                                        
          value: "KAFKA_API_SECRET_PLACEHOLDER"   
        name: app
        startupProbe:
          httpGet:
            path: /health
            port: 8000
        ports:
        - containerPort: 8000
      - image: "us-docker.pkg.dev/cloud-ops-agents-artifacts/cloud-run-gmp-sidecar/cloud-run-gmp-sidecar:1.2.0"
        name: collector