// Code generated by "stringer -type=AlertType"; DO NOT EDIT.

package alerts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[More-0]
	_ = x[Less-1]
}

const _AlertType_name = "MoreLess"

var _AlertType_index = [...]uint8{0, 4, 8}

func (i AlertType) String() string {
	if i < 0 || i >= AlertType(len(_AlertType_index)-1) {
		return "AlertType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AlertType_name[_AlertType_index[i]:_AlertType_index[i+1]]
}
